[package]
name = "cleanfolio-v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cleanfolio = "0.1.0"
sentry = "0.34.0"

[lib]
name = "Cleanfolio-v2"
path = "lib.rs"
