[package]
name = "ece"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = "0.34.0"
secp256k1 = "0.21"

[lib]
name = "ece"
path = "lib.rs"
