<<<<<<< HEAD
[package]
name = "ece"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = "0.34.0"
secp256k1 = "0.21"

[lib]
name = "ece"
path = "lib.rs"
=======
[workspace]
members = [
    "bitcell",
    "thepublic",
    "nano-node",
    "txn-tracker",
    "socket-chat",
]
>>>>>>> a99842ae8ecbc6004289317e6f3875bd16d6b7ef
