// Marketplace demo data
export const demoMarketplaceProducts = [
  {
    id: 1,
    title: "Blockchain Analytics Dashboard",
    description: "Comprehensive analytics for blockchain transactions and smart contracts.",
    category: "Analytics",
    price: 50,
    currency: "ECE",
    rating: 4.7,
    reviews: 28,
    image: "/images/products/analytics-dashboard.png",
    seller: {
      name: "BlockVision Inc.",
      verified: true,
      joinedDate: "2022-03-15",
    },
  },
  {
    id: 2,
    title: "Smart Contract Security Scanner",
    description: "Automated security analysis for smart contracts with vulnerability detection.",
    category: "Security",
    price: 75,
    currency: "ECE",
    rating: 4.9,
    reviews: 42,
    image: "/images/products/security-scanner.png",
    seller: {
      name: "SecureChain",
      verified: true,
      joinedDate: "2021-11-08",
    },
  },
  {
    id: 3,
    title: "DeFi Portfolio Manager",
    description: "Track and optimize your DeFi investments across multiple protocols.",
    category: "Finance",
    price: 60,
    currency: "ECE",
    rating: 4.5,
    reviews: 36,
    image: "/images/products/defi-portfolio.png",
    seller: {
      name: "DeFi Labs",
      verified: true,
      joinedDate: "2022-01-22",
    },
  },
  {
    id: 4,
    title: "NFT Minting Platform",
    description: "Create and deploy NFT collections with customizable smart contracts.",
    category: "Development",
    price: 85,
    currency: "ECE",
    rating: 4.6,
    reviews: 19,
    image: "/images/products/nft-platform.png",
    seller: {
      name: "NFT Forge",
      verified: false,
      joinedDate: "2022-05-30",
    },
  },
  {
    id: 5,
    title: "Cross-Chain Bridge SDK",
    description: "Integrate cross-chain functionality into your dApps with our easy-to-use SDK.",
    category: "Development",
    price: 120,
    currency: "ECE",
    rating: 4.8,
    reviews: 15,
    image: "/images/products/blockchain-bridge.png",
    seller: {
      name: "ChainLink Solutions",
      verified: true,
      joinedDate: "2021-09-14",
    },
  },
  {
    id: 6,
    title: "Blockchain Data Indexer",
    description: "High-performance indexing solution for blockchain data with GraphQL API.",
    category: "Analytics",
    price: 95,
    currency: "ECE",
    rating: 4.4,
    reviews: 23,
    image: "/images/products/data-indexer.png",
    seller: {
      name: "IndexChain",
      verified: true,
      joinedDate: "2022-02-11",
    },
  },
]

export const demoMarketplaceCategories = [
  { id: "analytics", name: "Analytics", count: 24 },
  { id: "security", name: "Security", count: 18 },
  { id: "finance", name: "Finance", count: 32 },
  { id: "development", name: "Development", count: 45 },
  { id: "nft", name: "NFT", count: 27 },
  { id: "defi", name: "DeFi", count: 36 },
]

// Crowdfunding demo data with milestones
export const demoCrowdfundingProjects = [
  {
    id: 1,
    title: "Decentralized Identity Solution",
    description: "A self-sovereign identity platform built on blockchain technology.",
    raised: 12500,
    goal: 20000,
    backers: 78,
    daysLeft: 14,
    creator: "IdentityDAO",
    category: "Identity",
    image: "/images/projects/identity-solution.png",
    updates: 3,
    createdAt: "2023-04-15",
    milestones: [
      {
        percentage: 25,
        title: "Core Protocol Development",
        description: "Develop the foundational identity protocol and smart contracts.",
      },
      {
        percentage: 50,
        title: "Mobile SDK Release",
        description: "Release SDK for iOS and Android integration with documentation.",
      },
      {
        percentage: 75,
        title: "Identity Verification Partners",
        description: "Integrate with 3 major identity verification providers.",
      },
      {
        percentage: 100,
        title: "Public Beta Launch",
        description: "Launch public beta with full feature set and developer documentation.",
      },
    ],
  },
  {
    id: 2,
    title: "Cross-Chain DeFi Protocol",
    description: "Seamlessly trade assets across multiple blockchains with low fees.",
    raised: 35000,
    goal: 50000,
    backers: 142,
    daysLeft: 21,
    creator: "CrossChain Labs",
    category: "DeFi",
    image: "/images/projects/defi-protocol.png",
    updates: 5,
    createdAt: "2023-03-22",
    milestones: [
      {
        percentage: 25,
        title: "Protocol Design & Architecture",
        description: "Complete protocol design, security model, and technical architecture.",
      },
      {
        percentage: 50,
        title: "Smart Contract Development",
        description: "Develop and audit core smart contracts for cross-chain swaps.",
      },
      {
        percentage: 75,
        title: "Multi-Chain Integration",
        description: "Integrate with Ethereum, Solana, Polygon, and Binance Smart Chain.",
      },
      {
        percentage: 100,
        title: "Trading Interface Launch",
        description: "Launch user interface with liquidity pools and cross-chain trading.",
      },
    ],
  },
  {
    id: 3,
    title: "NFT Gaming Platform",
    description: "Play-to-earn gaming platform with tradable NFT assets.",
    raised: 18000,
    goal: 25000,
    backers: 95,
    daysLeft: 7,
    creator: "GameBlock Studios",
    category: "Gaming",
    image: "/images/projects/nft-gaming.png",
    updates: 2,
    createdAt: "2023-05-01",
    milestones: [
      {
        percentage: 25,
        title: "Game Engine Development",
        description: "Build core game engine with NFT integration and asset management.",
      },
      {
        percentage: 50,
        title: "NFT Marketplace",
        description: "Develop in-game NFT marketplace for trading game assets.",
      },
      {
        percentage: 75,
        title: "Alpha Game Release",
        description: "Release alpha version with basic gameplay and NFT functionality.",
      },
      {
        percentage: 100,
        title: "Full Game Launch",
        description: "Launch complete game with play-to-earn mechanics and tournaments.",
      },
    ],
  },
  {
    id: 4,
    title: "Zero-Knowledge Privacy Layer",
    description: "Add privacy to any blockchain with our zero-knowledge proof implementation.",
    raised: 42000,
    goal: 60000,
    backers: 156,
    daysLeft: 30,
    creator: "ZK Innovations",
    category: "Privacy",
    image: "/images/projects/zero-knowledge.png",
    updates: 4,
    createdAt: "2023-02-28",
    milestones: [
      {
        percentage: 25,
        title: "ZK-Proof Library",
        description: "Develop optimized zero-knowledge proof library for blockchain integration.",
      },
      {
        percentage: 50,
        title: "Privacy Protocol",
        description: "Build privacy protocol with transaction shielding and anonymous transfers.",
      },
      {
        percentage: 75,
        title: "Multi-Chain Support",
        description: "Add support for Ethereum, Polygon, and other EVM-compatible chains.",
      },
      {
        percentage: 100,
        title: "Developer Tools & SDK",
        description: "Release comprehensive SDK and developer tools for easy integration.",
      },
    ],
  },
  {
    id: 5,
    title: "Decentralized Storage Network",
    description: "Community-owned storage network with encryption and data sharding.",
    raised: 28500,
    goal: 40000,
    backers: 112,
    daysLeft: 18,
    creator: "StorageDAO",
    category: "Infrastructure",
    image: "/images/projects/decentralized-storage.png",
    updates: 6,
    createdAt: "2023-04-05",
    milestones: [
      {
        percentage: 25,
        title: "Storage Protocol Design",
        description: "Design storage protocol with encryption, sharding, and node incentives.",
      },
      {
        percentage: 50,
        title: "Node Software Development",
        description: "Develop node software for storage providers with resource management.",
      },
      {
        percentage: 75,
        title: "Client Libraries",
        description: "Create client libraries for JavaScript, Python, and Rust with examples.",
      },
      {
        percentage: 100,
        title: "Mainnet Launch",
        description: "Launch mainnet with 100+ storage nodes and full encryption support.",
      },
    ],
  },
  {
    id: 6,
    title: "Blockchain Social Media Platform",
    description: "Censorship-resistant social media with user-owned data and monetization.",
    raised: 15800,
    goal: 30000,
    backers: 89,
    daysLeft: 25,
    creator: "SocialChain",
    category: "Social",
    image: "/images/projects/blockchain-social.png",
    updates: 3,
    createdAt: "2023-05-10",
    milestones: [
      {
        percentage: 25,
        title: "Protocol Development",
        description: "Develop social graph protocol and content storage system.",
      },
      {
        percentage: 50,
        title: "Web Application",
        description: "Build web application with core social features and wallet integration.",
      },
      {
        percentage: 75,
        title: "Creator Monetization",
        description: "Implement creator monetization tools with token-based subscriptions.",
      },
      {
        percentage: 100,
        title: "Mobile Apps & Federation",
        description: "Launch mobile apps and federation protocol for cross-platform interaction.",
      },
    ],
  },
]

// User demo data
export const demoUsers = [
  {
    id: "user1",
    name: "Demo User",
    email: "demo@example.com",
    avatar: "/diverse-user-avatars.png",
    balance: 1250,
    currency: "ECE",
    joinedDate: "2023-01-15",
  },
]

// User transactions demo data
export const demoTransactions = [
  {
    id: "tx1",
    type: "purchase",
    amount: 75,
    currency: "ECE",
    description: "Smart Contract Security Scanner",
    date: "2023-05-12T14:30:00Z",
    status: "completed",
  },
  {
    id: "tx2",
    type: "funding",
    amount: 50,
    currency: "ECE",
    description: "Backed: Decentralized Identity Solution",
    date: "2023-05-10T09:15:00Z",
    status: "completed",
  },
  {
    id: "tx3",
    type: "deposit",
    amount: 200,
    currency: "ECE",
    description: "Deposit from external wallet",
    date: "2023-05-05T11:45:00Z",
    status: "completed",
  },
  {
    id: "tx4",
    type: "withdrawal",
    amount: 100,
    currency: "ECE",
    description: "Withdrawal to external wallet",
    date: "2023-04-28T16:20:00Z",
    status: "completed",
  },
  {
    id: "tx5",
    type: "purchase",
    amount: 60,
    currency: "ECE",
    description: "DeFi Portfolio Manager",
    date: "2023-04-22T13:10:00Z",
    status: "completed",
  },
]

// User notifications demo data
export const demoNotifications = [
  {
    id: "notif1",
    title: "Purchase Successful",
    message: "You have successfully purchased Smart Contract Security Scanner.",
    date: "2023-05-12T14:30:00Z",
    read: true,
  },
  {
    id: "notif2",
    title: "Project Update",
    message: "Decentralized Identity Solution has posted a new update.",
    date: "2023-05-11T10:45:00Z",
    read: false,
  },
  {
    id: "notif3",
    title: "Funding Successful",
    message: "Your funding of Decentralized Identity Solution was successful.",
    date: "2023-05-10T09:15:00Z",
    read: true,
  },
  {
    id: "notif4",
    title: "New Product Available",
    message: "A new product in your watchlist is now available: Blockchain Data Indexer.",
    date: "2023-05-08T15:20:00Z",
    read: false,
  },
  {
    id: "notif5",
    title: "Deposit Confirmed",
    message: "Your deposit of 200 ECE has been confirmed.",
    date: "2023-05-05T11:45:00Z",
    read: true,
  },
]

// Mock GitHub repository data
export const mockGitHubRepository = {
  id: "repo-001",
  name: "next-auth",
  owner: "nextjs-corp",
  description: "Authentication for Next.js",
  url: "https://github.com/nextjs-corp/next-auth",
  stars: 15200,
  forks: 1800,
  openIssues: 85,
  watchers: 320,
  defaultBranch: "main",
  createdAt: "2020-01-15T10:30:00Z",
  updatedAt: "2023-05-20T14:25:00Z",
  language: "TypeScript",
  isPrivate: false,
  size: 12500,
  topics: ["authentication", "nextjs", "react", "oauth"],
  license: "MIT",
  hasWiki: true,
  hasPages: true,
  hasProjects: true,
  hasDownloads: true,
  archived: false,
  disabled: false,
  visibility: "public",
  branches: [
    { name: "main", isDefault: true },
    { name: "develop", isDefault: false },
    { name: "feature/marketplace", isDefault: false },
  ],
  commits: [
    {
      id: "c1",
      message: "Add wallet balance display and transaction history",
      author: {
        name: "Jane Developer",
        avatar: "/diverse-group.png",
        username: "janedeveloper",
      },
      date: "2023-05-20T14:30:00Z",
      sha: "a1b2c3d4e5f6g7h8i9j0",
      branch: "feature/wallet",
    },
    {
      id: "c2",
      message: "Fix responsive layout issues on marketplace page",
      author: {
        name: "John Coder",
        avatar: "/diverse-group.png",
        username: "johncoder",
      },
      date: "2023-05-19T10:15:00Z",
      sha: "b2c3d4e5f6g7h8i9j0k1",
      branch: "feature/marketplace",
    },
    {
      id: "c3",
      message: "Merge pull request #15 from feature/wallet",
      author: {
        name: "Team Lead",
        avatar: "/diverse-group.png",
        username: "teamlead",
      },
      date: "2023-05-18T09:45:00Z",
      sha: "c3d4e5f6g7h8i9j0k1l2",
      branch: "main",
    },
  ],
  pullRequests: [
    {
      id: "pr1",
      title: "Add marketplace search functionality",
      number: 16,
      author: {
        name: "John Coder",
        avatar: "/diverse-group.png",
        username: "johncoder",
      },
      status: "open",
      createdAt: "2023-05-19T14:30:00Z",
      updatedAt: "2023-05-19T16:20:00Z",
      branch: "feature/marketplace",
      targetBranch: "develop",
      comments: 3,
    },
    {
      id: "pr2",
      title: "Implement wallet notifications",
      number: 15,
      author: {
        name: "Jane Developer",
        avatar: "/diverse-group.png",
        username: "janedeveloper",
      },
      status: "merged",
      createdAt: "2023-05-16T11:30:00Z",
      updatedAt: "2023-05-18T09:45:00Z",
      branch: "feature/wallet",
      targetBranch: "main",
      comments: 5,
    },
  ],
  issues: [
    {
      id: "i1",
      title: "Mobile navigation menu not working on iOS",
      number: 23,
      author: {
        name: "QA Tester",
        avatar: "/diverse-group.png",
        username: "qatester",
      },
      status: "open",
      createdAt: "2023-05-17T16:20:00Z",
      updatedAt: "2023-05-19T14:30:00Z",
      labels: [
        { name: "bug", color: "d73a4a" },
        { name: "mobile", color: "0075ca" },
        { name: "priority: high", color: "b60205" },
      ],
      comments: 2,
      assignees: [
        {
          name: "John Coder",
          avatar: "/diverse-group.png",
          username: "johncoder",
        },
      ],
    },
    {
      id: "i2",
      title: "Add dark mode support",
      number: 22,
      author: {
        name: "UI Designer",
        avatar: "/diverse-group.png",
        username: "uidesigner",
      },
      status: "closed",
      createdAt: "2023-05-15T11:30:00Z",
      updatedAt: "2023-05-16T16:20:00Z",
      labels: [
        { name: "enhancement", color: "a2eeef" },
        { name: "ui", color: "7057ff" },
      ],
      comments: 4,
      assignees: [
        {
          name: "Jane Developer",
          avatar: "/diverse-group.png",
          username: "janedeveloper",
        },
      ],
    },
  ],
}

// Mock data for Vercel projects
export const mockVercelProject = {
  id: "proj_1",
  name: "ece-app",
  framework: "Next.js",
  url: "https://vercel.com/yourusername/ece-app",
  productionBranch: "main",
  team: {
    name: "Your Team",
    slug: "your-team",
  },
  domains: [
    { name: "ece-app.vercel.app", verified: true, primary: true },
    { name: "ece-app.com", verified: true, primary: false },
    { name: "www.ece-app.com", verified: true, primary: false },
  ],
  latestDeployment: {
    id: "dpl_1",
    url: "https://ece-app.vercel.app",
    name: "Production Deployment",
    status: "ready",
    createdAt: "2023-05-20T14:30:00Z",
    readyAt: "2023-05-20T15:00:00Z",
    branch: "main",
    commit: {
      sha: "a1b2c3d4e5f6g7h8i9j0",
      message: "Merge pull request #15 from feature/wallet",
      author: "teamlead",
    },
    meta: {
      buildTime: 120000, // 2 minutes
      region: "sfo1",
      framework: "Next.js",
      nodeVersion: "18.x",
    },
  },
  deployments: [
    {
      id: "dpl_1",
      url: "https://ece-app.vercel.app",
      name: "Production Deployment",
      status: "ready",
      createdAt: "2023-05-20T14:30:00Z",
      readyAt: "2023-05-20T15:00:00Z",
      branch: "main",
      commit: {
        sha: "a1b2c3d4e5f6g7h8i9j0",
        message: "Merge pull request #15 from feature/wallet",
        author: "teamlead",
      },
      meta: {
        buildTime: 120000, // 2 minutes
        region: "sfo1",
        framework: "Next.js",
        nodeVersion: "18.x",
      },
    },
    {
      id: "dpl_2",
      url: "https://feature-marketplace-ece-app.vercel.app",
      name: "Preview Deployment",
      status: "ready",
      createdAt: "2023-05-19T10:15:00Z",
      readyAt: "2023-05-19T11:45:00Z",
      branch: "feature/marketplace",
      commit: {
        sha: "b2c3d4e5f6g7h8i9j0k1",
        message: "Fix responsive layout issues on marketplace page",
        author: "johncoder",
      },
      meta: {
        buildTime: 105000, // 1.75 minutes
        region: "sfo1",
        framework: "Next.js",
        nodeVersion: "18.x",
      },
    },
    {
      id: "dpl_3",
      url: "",
      name: "Preview Deployment",
      status: "error",
      createdAt: "2023-05-17T09:45:00Z",
      branch: "feature/experimental",
      commit: {
        sha: "d4e5f6g7h8i9j0k1l2m3",
        message: "Experimental feature implementation",
        author: "janedeveloper",
      },
      meta: {
        region: "sfo1",
        framework: "Next.js",
        nodeVersion: "18.x",
      },
    },
  ],
}

export const demoScheduledDeposits = [
  {
    id: "sd1",
    amount: 100,
    currency: "ECE",
    frequency: "weekly",
    nextExecutionDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Weekly savings deposit",
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sd2",
    amount: 50,
    currency: "ECE",
    frequency: "biweekly",
    nextExecutionDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Biweekly emergency fund",
    isActive: true,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sd3",
    amount: 75,
    currency: "ECE",
    frequency: "monthly",
    nextExecutionDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Monthly investment",
    isActive: false,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const demoCrowdfundingCategories = [
  { id: "defi", name: "DeFi", count: 24 },
  { id: "nft", name: "NFT", count: 18 },
  { id: "gaming", name: "Gaming", count: 32 },
  { id: "identity", name: "Identity", count: 45 },
  { id: "infrastructure", name: "Infrastructure", count: 27 },
  { id: "analytics", name: "Analytics", count: 36 },
]
