export const mockApps = [
  {
    id: "app-1",
    name: "DeFi Protocol",
    description: "A decentralized finance protocol for lending and borrowing crypto assets",
    status: "active",
    deployments: 12,
    lastDeployed: "2023-04-15T10:30:00Z",
    version: "1.2.3",
    resourceUsage: {
      cpu: 45,
      memory: 512,
      storage: 2.5,
      bandwidth: 150,
    },
    users: 1250,
    logs: {
      errors: 2,
      warnings: 5,
      info: 120,
    },
    backups: [
      { id: "backup-1", date: "2023-04-10T00:00:00Z", size: "1.2GB", status: "completed" },
      { id: "backup-2", date: "2023-04-03T00:00:00Z", size: "1.1GB", status: "completed" },
      { id: "backup-3", date: "2023-03-27T00:00:00Z", size: "1.0GB", status: "completed" },
    ],
    integrations: [
      { id: "int-1", name: "GitHub", status: "connected" },
      { id: "int-2", name: "Vercel", status: "connected" },
      { id: "int-3", name: "Supabase", status: "connected" },
    ],
  },
  {
    id: "app-2",
    name: "NFT Marketplace",
    description: "A platform for creating, buying, and selling NFTs",
    status: "active",
    deployments: 8,
    lastDeployed: "2023-04-12T14:45:00Z",
    version: "0.9.5",
    resourceUsage: {
      cpu: 60,
      memory: 768,
      storage: 5.2,
      bandwidth: 320,
    },
    users: 3450,
    logs: {
      errors: 1,
      warnings: 8,
      info: 210,
    },
    backups: [
      { id: "backup-4", date: "2023-04-11T00:00:00Z", size: "2.5GB", status: "completed" },
      { id: "backup-5", date: "2023-04-04T00:00:00Z", size: "2.4GB", status: "completed" },
      { id: "backup-6", date: "2023-03-28T00:00:00Z", size: "2.3GB", status: "completed" },
    ],
    integrations: [
      { id: "int-4", name: "GitHub", status: "connected" },
      { id: "int-5", name: "Vercel", status: "connected" },
      { id: "int-6", name: "AWS S3", status: "connected" },
    ],
  },
  {
    id: "app-3",
    name: "Blockchain Bridge",
    description: "A cross-chain bridge for transferring assets between blockchains",
    status: "maintenance",
    deployments: 15,
    lastDeployed: "2023-04-08T09:15:00Z",
    version: "2.0.1",
    resourceUsage: {
      cpu: 75,
      memory: 1024,
      storage: 3.8,
      bandwidth: 280,
    },
    users: 2100,
    logs: {
      errors: 5,
      warnings: 12,
      info: 180,
    },
    backups: [
      { id: "backup-7", date: "2023-04-07T00:00:00Z", size: "1.8GB", status: "completed" },
      { id: "backup-8", date: "2023-03-31T00:00:00Z", size: "1.7GB", status: "completed" },
      { id: "backup-9", date: "2023-03-24T00:00:00Z", size: "1.7GB", status: "completed" },
    ],
    integrations: [
      { id: "int-7", name: "GitHub", status: "connected" },
      { id: "int-8", name: "Vercel", status: "connected" },
      { id: "int-9", name: "Infura", status: "connected" },
    ],
  },
]
