[package]
name = "near-hello"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "3.1.0"
near-sdk-macros = "3.1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"