name: Continuous Deployment

on:
  push:
    branches:
      - main # Deploy when there's a push to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Latest LTS Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 'lts/*' # This will use the latest LTS version of Node.js
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Project
        run: yarn build
      - name: Deploy to Production
        run: echo "Add your deployment script/command here"
        env:
          CI: true
          # Add any necessary environment variables here
          # DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
